const getChatroomData=()=>{
const users=['TheDustBwlDuck','mikeloveshalflife','xX_SC0UT_RULEZ_Xx','PYROMANIAC_99','dustbowlBOSS_admin','M3DIC_OR_RIOT','BONKBONKBONK','hevy_sandvich_man','spycrab_lol','sENTRY_gUY_420','cr1tical_h1t','hatcollector3000','dj_n00dles','backstabMASTA','cloakedNdaggerd','xx_FRAGZ_xx','n00bkillaXD','I_MAIN_EVERYTHING','2FORT_4EVER','PAYLOAD_PUSHR','sn1p3r_n0_sc0p3','ROCKETLAUNCHER69','iiiiillllllllll','xX_d4rkn3ss_Xx','lolwut07','BATSWINGIN55','xXdRuMzXx',
'UBER_EVERYTHING','dustbowl_newbie','the_real_gaben','W+M1_PYRO','snipin_is_a_good_job','MY_DAD_WORKS_AT_VALVE','random_crit_victim','trade_me_bro','idlebot9000','DOMINATED_AGAIN','airblast_this','uberchain','CART_GOES_BRRR','2007_veteran','sticky_spammer','NEED_A_DISPENSER','crit_happens','last_point_hero','cap_the_point_pls','flanking_scout','pybro_main','medic_gf','HEAVY_IS_CREDIT_TO_TEAM',
'no_random_crits_pls','votekick_started','server_lag_247','dustbowl_stage3_fan','tunnel_vision_guy','BONK_ATOMIC_PUNCH','sandvich_safe','cloak_n_dagger_camper','market_garden_master','crossbow_sniper','rescue_ranger_engi','quickfix_medic','jarate_thrower','AXTINGUISHER_NERF','deadringer_spy','gunslinger_engi','huntsman_main','loose_cannon_demo','natasha_heavy','shortstop_scout','tomislav_heavy','widowmaker_engi','wrangler_sentry','blutsauger_medic','overdose_speed','solemn_vow_medic','amputator_medic',
'gg_ez','NEED_HEALING','PUSH_THE_CART','spy_around_here','sentry_ahead','teleporter_here','pootis_spencer','STOUT_SHAKO','hat_simulator_2010','f2p_gibus','vintage_collector','craft_hat_plz','strange_weapon_guy','killstreak_king','domination_machine','taunt_after_kill','friendly_hoovy','CONGA_LINE','high_five_guy','rock_paper_scissors','kazotsky_kick','mannrobics_dancer',
'x360_controller','voice_chat_singer','mic_spammer_9000','ear_rape_kid','soundboard_guy','ADMIN_ABUSE','false_votekick','server_regular','first_time_here','just_installed_tf2','coming_from_cod','overwatch_refugee','css_veteran','gmod_builder','left4dead_fan','portal_speedrun','halflife3_when','ep3_believer','source2_when','valve_time_lol',
'bruh_moment','this_is_fine','gg_no_re','rage_quit_king','alt_f4_prank','bind_spam_kid','lenny_face_guy','xd_lol_rawr','uwu_medic','69_nice','420_blaze_scout','1337_h4x0r','noob_destroyer','pro_gamer_69','MLG_360','FaZe_wannabe','trickstab_god','matador_stab','stairstab_king','cornerstab_pro',
'turbine_enjoyer','hightower_jumper','harvest_sniper','nucleus_fan','viaduct_main','koth_king','plr_hightower','mvm_veteran','mann_up_mode','boot_camp_grinder','australium_hunter','golden_pan_dream','unusual_unboxer','key_trader','ref_beggar','scrap_banker','backpack_full','inventory_hoarder',
'gibusvision','gibus_pyrovision','mercenary_badge','grizzled_veteran','primeval_warrior','proof_of_purchase','earbuds_flex','max_head_rich','buds_economy','bill_hat_fan',
'demoknight_tf2','shield_bash','trimping_god','eyelander_heads','tide_turner_demo','charge_n_targe','persian_persuader','claidheamh_mor','half_zatoichi','mantreads_soldier','BASE_jumper','beggars_bazooka','liberty_launcher','direct_hit_only','stock_rocket_best','original_launcher',
'DISPENSER_GOING_UP','mini_sentry_spam','level3_sentry_nest','wrench_battle','jag_main','eureka_effect','southern_hospitality','frontier_justice','pomson_engi','short_circuit_spam',
'backburner_pyro','phlog_w_m1','degreaser_combo','flare_gun_crit','scorch_shot_spam','detonator_jump','third_degree_kill','neon_annihilator','powerjack_speed','homewrecker_pybro',
'force_a_nature','baby_face_blaster','soda_popper_jumps','wrap_assassin','flying_guillotine','cleaver_combo','boston_basher','three_rune_blade','atomizer_triple','crit_a_cola',
'bazaar_bargain','machina_bodyshot','sydney_sleeper','classic_charge','hitman_heatmaker','carbine_cozy','razorback_counter','darwins_shield','jarate_bushman','smg_enjoyer',
'iron_curtain','brass_beast','family_business','buffalo_steak','warriors_spirit','eviction_notice','fists_of_steel','holiday_punch','gloves_of_running','killing_gloves',
'stock_uber_best','vacc_bubble','quick_fix_surfer','kritz_or_uber','vita_saw_banned','crossbow_aim','crusaders_xbow','ubersaw_gamble','bonesaw_chad','amputator_taunt',
'loch_n_load','iron_bomber_main','quickie_launcher','scottish_resistance','stickytrap_king','ullapool_caber','caber_knight','pain_train','bottle_random_crit','golf_club_demo'];

const normal=[
{t:'7:00 PM',u:'dustbowlBOSS_admin',m:'Welcome to Dustbowl 24/7 Community Chat! Be nice or get banned.'},
{t:'7:00 PM',u:'server_regular',m:'hey everyone'},
{t:'7:01 PM',u:'TheDustBwlDuck',m:'ayyyy whats up chat'},
{t:'7:01 PM',u:'mikeloveshalflife',m:'yo duck'},
{t:'7:01 PM',u:'xX_SC0UT_RULEZ_Xx',m:'LETS GOOOO'},
{t:'7:02 PM',u:'PYROMANIAC_99',m:'FIRE'},
{t:'7:02 PM',u:'dustbowl_newbie',m:'hey im new here whats the best class'},
{t:'7:02 PM',u:'TheDustBwlDuck',m:'MEDIC obviously'},
{t:'7:02 PM',u:'xX_SC0UT_RULEZ_Xx',m:'SCOUT'},
{t:'7:02 PM',u:'PYROMANIAC_99',m:'PYRO'},
{t:'7:02 PM',u:'hevy_sandvich_man',m:'heavy'},
{t:'7:02 PM',u:'M3DIC_OR_RIOT',m:'MEDIC OR I RIOT'},
{t:'7:03 PM',u:'dustbowl_newbie',m:'ok so everyone just says their own class lol'},
{t:'7:03 PM',u:'cr1tical_h1t',m:'play soldier. trust me.'},
{t:'7:03 PM',u:'sn1p3r_n0_sc0p3',m:'sniper ez'},
{t:'7:03 PM',u:'backstabMASTA',m:'spy is the gentleman class'},
{t:'7:04 PM',u:'cloakedNdaggerd',m:'backstab sucks at spy dont listen to him'},
{t:'7:04 PM',u:'backstabMASTA',m:'HEY'},
{t:'7:04 PM',u:'TheDustBwlDuck',m:'lmaooo'},
{t:'7:05 PM',u:'hatcollector3000',m:'anyone wanna trade? i have 3 refined'},
{t:'7:05 PM',u:'hat_simulator_2010',m:'this game is just a hat simulator at this point'},
{t:'7:05 PM',u:'f2p_gibus',m:'whats refined'},
{t:'7:06 PM',u:'hatcollector3000',m:'oh no'},
{t:'7:06 PM',u:'vintage_collector',m:'smelt weapons kid'},
{t:'7:06 PM',u:'trade_me_bro',m:'ill give u a gibus for 2 keys'},
{t:'7:06 PM',u:'TheDustBwlDuck',m:'LOL thats a scam every1 has a gibus'},
{t:'7:07 PM',u:'BONKBONKBONK',m:'BONK'},
{t:'7:07 PM',u:'BONK_ATOMIC_PUNCH',m:'BONK'},
{t:'7:07 PM',u:'BONKBONKBONK',m:'ayyyy my bonk brother'},
{t:'7:08 PM',u:'NEED_A_DISPENSER',m:'NEED A DISPENSER HERE'},
{t:'7:08 PM',u:'gunslinger_engi',m:'no'},
{t:'7:08 PM',u:'NEED_A_DISPENSER',m:'NEED A DISPENSER HERE'},
{t:'7:08 PM',u:'NEED_A_DISPENSER',m:'NEED A DISPENSER HERE'},
{t:'7:08 PM',u:'dustbowlBOSS_admin',m:'stop spamming'},
{t:'7:09 PM',u:'pootis_spencer',m:'pootis spencer here'},
{t:'7:09 PM',u:'hevy_sandvich_man',m:'sandvich'},
{t:'7:09 PM',u:'friendly_hoovy',m:'i am friendly! dont shoot!'},
{t:'7:10 PM',u:'W+M1_PYRO',m:'*burns everything*'},
{t:'7:10 PM',u:'phlog_w_m1',m:'mmph mmph mmph'},
{t:'7:10 PM',u:'airblast_this',m:'can someone please airblast the rockets'},
{t:'7:10 PM',u:'W+M1_PYRO',m:'no i only w+m1'},
{t:'7:11 PM',u:'TheDustBwlDuck',m:'i uberd a pyro once. never again.'},
{t:'7:11 PM',u:'M3DIC_OR_RIOT',m:'WORST MISTAKE U CAN MAKE'},
{t:'7:11 PM',u:'quickfix_medic',m:'quick fix is underrated btw'},
{t:'7:12 PM',u:'TheDustBwlDuck',m:'kritz gang rise up'},
{t:'7:12 PM',u:'stock_uber_best',m:'stock uber or nothing'},
{t:'7:12 PM',u:'kritz_or_uber',m:'kritz on defense stock on offense'},
{t:'7:12 PM',u:'ubersaw_gamble',m:'just ubersaw 4head'},
{t:'7:13 PM',u:'crossbow_aim',m:'crossbow is the best weapon in the game change my mind'},
{t:'7:13 PM',u:'TheDustBwlDuck',m:'UBERSAW is the best weapon in the game change MY mind'},
{t:'7:14 PM',u:'sENTRY_gUY_420',m:'sENTRY iS tHE bEST wEAPON'},
{t:'7:14 PM',u:'mini_sentry_spam',m:'mini sentries go brrrr'},
{t:'7:14 PM',u:'DISPENSER_GOING_UP',m:'DISPENSER GOING UP'},
{t:'7:15 PM',u:'spy_around_here',m:'spy!'},
{t:'7:15 PM',u:'backstabMASTA',m:'where'},
{t:'7:15 PM',u:'cloakedNdaggerd',m:'lol he means u'},
{t:'7:15 PM',u:'backstabMASTA',m:'oh'},
{t:'7:16 PM',u:'random_crit_victim',m:'I JUST DIED TO A RANDOM CRIT AGAIN'},
{t:'7:16 PM',u:'crit_happens',m:'skill issue'},
{t:'7:16 PM',u:'no_random_crits_pls',m:'random crits should be removed'},
{t:'7:16 PM',u:'random_crit_victim',m:'HE HIT ME WITH A WRENCH FROM ACROSS THE MAP'},
{t:'7:17 PM',u:'TheDustBwlDuck',m:'lol get rekt'},
{t:'7:17 PM',u:'gg_ez',m:'gg ez'},
{t:'7:17 PM',u:'rage_quit_king',m:'im done with this game'},
{t:'7:17 PM',u:'rage_quit_king',m:'*rage_quit_king has left the chat*'},
{t:'7:17 PM',u:'rage_quit_king',m:'*rage_quit_king has joined the chat*'},
{t:'7:18 PM',u:'TheDustBwlDuck',m:'that was fast lol'},
{t:'7:18 PM',u:'mikeloveshalflife',m:'lmaoooo'},
{t:'7:18 PM',u:'bruh_moment',m:'bruh'},
{t:'7:19 PM',u:'the_real_gaben',m:'half life 3 confirmed'},
{t:'7:19 PM',u:'halflife3_when',m:'REALLY???'},
{t:'7:19 PM',u:'the_real_gaben',m:'no lol'},
{t:'7:19 PM',u:'halflife3_when',m:'i hate u'},
{t:'7:19 PM',u:'ep3_believer',m:'one day...'},
{t:'7:20 PM',u:'valve_time_lol',m:'valve time baby'},
{t:'7:20 PM',u:'market_garden_master',m:'just got a sick market garden'},
{t:'7:20 PM',u:'mantreads_soldier',m:'mantreads > market gardener'},
{t:'7:20 PM',u:'direct_hit_only',m:'direct hit or nothing'},
{t:'7:21 PM',u:'stock_rocket_best',m:'stock launcher is better than all of those'},
{t:'7:21 PM',u:'beggars_bazooka',m:'beggars goes brrrrr'},
{t:'7:21 PM',u:'BASE_jumper',m:'base jumper + beggars = air force'},
{t:'7:22 PM',u:'DOMINATED_AGAIN',m:'THAT SCOUT JUST DOMINATED ME FOR THE 4TH TIME'},
{t:'7:22 PM',u:'flanking_scout',m:'git gud'},
{t:'7:22 PM',u:'force_a_nature',m:'*double jumps past u*'},
{t:'7:23 PM',u:'baby_face_blaster',m:'baby face is so fun when its charged'},
{t:'7:23 PM',u:'crit_a_cola',m:'crit a cola is balanced i swear'},
{t:'7:23 PM',u:'boston_basher',m:'i keep hitting myself with the basher'},
{t:'7:24 PM',u:'TheDustBwlDuck',m:'the basher is 4 building uber not hitting ppl lol'},
{t:'7:24 PM',u:'M3DIC_OR_RIOT',m:'THIS GUY KNOWS'},
{t:'7:24 PM',u:'mikeloveshalflife',m:'duck ur such a medic nerd'},
{t:'7:25 PM',u:'TheDustBwlDuck',m:'and PROUD of it'},
{t:'7:25 PM',u:'demoknight_tf2',m:'DEMOKNIGHT TF2'},
{t:'7:25 PM',u:'demoknight_tf2',m:'DEMOKNIGHT TF2'},
{t:'7:25 PM',u:'demoknight_tf2',m:'DEMOKNIGHT TF2'},
{t:'7:26 PM',u:'eyelander_heads',m:'i got 4 heads im so fast'},
{t:'7:26 PM',u:'trimping_god',m:'trimping is an art form'},
{t:'7:26 PM',u:'tide_turner_demo',m:'tide turner best shield'},
{t:'7:27 PM',u:'sticky_spammer',m:'stickies > everything'},
{t:'7:27 PM',u:'iron_bomber_main',m:'iron bomber hitbox is broken and i love it'},
{t:'7:27 PM',u:'loch_n_load',m:'loch n load 2 shot combo'},
{t:'7:28 PM',u:'CONGA_LINE',m:'CONGA CONGA CONGA'},
{t:'7:28 PM',u:'kazotsky_kick',m:'*kazotsky kicks*'},
{t:'7:28 PM',u:'high_five_guy',m:'high five anyone?'},
{t:'7:28 PM',u:'taunt_after_kill',m:'*taunts*'},
{t:'7:28 PM',u:'TheDustBwlDuck',m:'i joined the conga lol'},
{t:'7:29 PM',u:'PYROMANIAC_99',m:'*burns the conga line*'},
{t:'7:29 PM',u:'TheDustBwlDuck',m:'PYRO WHY'},
{t:'7:29 PM',u:'PYROMANIAC_99',m:'FIRE DOESNT DISCRIMINATE'},
{t:'7:30 PM',u:'friendly_hoovy',m:'why u kill friendly :('},
{t:'7:30 PM',u:'W+M1_PYRO',m:'if it moves it burns'},
{t:'7:30 PM',u:'homewrecker_pybro',m:'pybros dont do that. we protect engis.'},
{t:'7:31 PM',u:'spycrab_lol',m:'*does the spycrab walk*'},
{t:'7:31 PM',u:'spycrab_lol',m:'*gets shot*'},
{t:'7:31 PM',u:'spycrab_lol',m:'NOOO I WAS FRIENDLY'},
{t:'7:32 PM',u:'bazaar_bargain',m:'sorry force of habit'},
{t:'7:32 PM',u:'machina_bodyshot',m:'bodyshots count'},
{t:'7:32 PM',u:'sn1p3r_n0_sc0p3',m:'NOSCOPE OR NOTHING'},
{t:'7:32 PM',u:'sydney_sleeper',m:'jarate sniper best sniper'},
{t:'7:33 PM',u:'jarate_thrower',m:'jarate is disgusting and i love it'},
{t:'7:33 PM',u:'snipin_is_a_good_job',m:'snipin is a good job mate'},
{t:'7:34 PM',u:'mic_spammer_9000',m:'*plays music thru mic*'},
{t:'7:34 PM',u:'dustbowlBOSS_admin',m:'muted'},
{t:'7:34 PM',u:'voice_chat_singer',m:'but i was singing well'},
{t:'7:34 PM',u:'dustbowlBOSS_admin',m:'u were not'},
{t:'7:35 PM',u:'2007_veteran',m:'i remember when this game was good'},
{t:'7:35 PM',u:'just_installed_tf2',m:'i just started playing whats happening'},
{t:'7:35 PM',u:'TheDustBwlDuck',m:'welcome 2 the best game ever made'},
{t:'7:36 PM',u:'coming_from_cod',m:'this game is so different from cod'},
{t:'7:36 PM',u:'css_veteran',m:'source engine gang'},
{t:'7:36 PM',u:'gmod_builder',m:'anyone play gmod'},
{t:'7:37 PM',u:'left4dead_fan',m:'l4d2 > l4d1 dont @ me'},
{t:'7:37 PM',u:'portal_speedrun',m:'just beat portal in 14 minutes'},
{t:'7:37 PM',u:'TheDustBwlDuck',m:'waht how'},
{t:'7:38 PM',u:'cap_the_point_pls',m:'CAN SOMEONE PLEASE CAP THE POINT'},
{t:'7:38 PM',u:'PUSH_THE_CART',m:'PUSH THE CART'},
{t:'7:38 PM',u:'last_point_hero',m:'ill cap it dw'},
{t:'7:39 PM',u:'tunnel_vision_guy',m:'WHY IS THERE A SENTRY IN THE TUNNEL'},
{t:'7:39 PM',u:'sENTRY_gUY_420',m:'hEHE'},
{t:'7:39 PM',u:'TheDustBwlDuck',m:'classic sentry guy'},
{t:'7:40 PM',u:'server_lag_247',m:'anyone else lagging'},
{t:'7:40 PM',u:'x360_controller',m:'im playing on controller btw'},
{t:'7:40 PM',u:'TheDustBwlDuck',m:'HOW'},
{t:'7:40 PM',u:'mikeloveshalflife',m:'mad respect tbh'},
{t:'7:41 PM',u:'MY_DAD_WORKS_AT_VALVE',m:'my dad works at valve and he said hl3 is real'},
{t:'7:41 PM',u:'the_real_gaben',m:'no i dont'},
{t:'7:41 PM',u:'TheDustBwlDuck',m:'LMAOOOO'},
{t:'7:42 PM',u:'killstreak_king',m:'19 killstreak rn nobody kill me pls'},
{t:'7:42 PM',u:'domination_machine',m:'*dominates killstreak_king*'},
{t:'7:42 PM',u:'killstreak_king',m:'NOOOO'},
{t:'7:43 PM',u:'STOUT_SHAKO',m:'STOUT SHAKO FOR 2 REFINED'},
{t:'7:43 PM',u:'ref_beggar',m:'can someone give me a ref pls'},
{t:'7:43 PM',u:'scrap_banker',m:'no'},
{t:'7:44 PM',u:'unusual_unboxer',m:'just unboxed a burning flames team captain'},
{t:'7:44 PM',u:'golden_pan_dream',m:'pic or it didnt happen'},
{t:'7:44 PM',u:'unusual_unboxer',m:'ok i lied it was a crate'},
{t:'7:45 PM',u:'TheDustBwlDuck',m:'i wud sell my soul 4 an unusual'},
{t:'7:45 PM',u:'mikeloveshalflife',m:'dont say that lol'},
{t:'7:46 PM',u:'CART_GOES_BRRR',m:'THE CART ISNT PUSHING ITSELF PEOPLE'},
{t:'7:46 PM',u:'idlebot9000',m:'...'},
{t:'7:46 PM',u:'dustbowlBOSS_admin',m:'is that an idle bot'},
{t:'7:46 PM',u:'idlebot9000',m:'no im real i swear'},
{t:'7:47 PM',u:'mvm_veteran',m:'anyone wanna do mvm later'},
{t:'7:47 PM',u:'mann_up_mode',m:'mann up or boot camp'},
{t:'7:47 PM',u:'boot_camp_grinder',m:'boot camp is free'},
{t:'7:48 PM',u:'australium_hunter',m:'i need an australium so bad'},
{t:'7:48 PM',u:'golden_pan_dream',m:'golden pan or nothing'},
{t:'7:49 PM',u:'2FORT_4EVER',m:'come play 2fort'},
{t:'7:49 PM',u:'TheDustBwlDuck',m:'no'},
{t:'7:49 PM',u:'2FORT_4EVER',m:'please'},
{t:'7:49 PM',u:'TheDustBwlDuck',m:'dustbowl or nothing'},
{t:'7:50 PM',u:'turbine_enjoyer',m:'turbine is the best map actually'},
{t:'7:50 PM',u:'hightower_jumper',m:'hightower trolldier time'},
{t:'7:50 PM',u:'harvest_sniper',m:'harvest is sniper paradise'},
{t:'7:51 PM',u:'TheDustBwlDuck',m:'DUSTBOWL > ALL OTHER MAPS'},
{t:'7:51 PM',u:'dustbowl_stage3_fan',m:'stage 3 last point is peak tf2'},
{t:'7:51 PM',u:'TheDustBwlDuck',m:'THIS GUY GETS IT'},
{t:'7:52 PM',u:'bind_spam_kid',m:'GET DUSTBOWLED LMAO'},
{t:'7:52 PM',u:'bind_spam_kid',m:'GET DUSTBOWLED LMAO'},
{t:'7:52 PM',u:'bind_spam_kid',m:'GET DUSTBOWLED LMAO'},
{t:'7:52 PM',u:'dustbowlBOSS_admin',m:'one more time and ur muted'},
{t:'7:52 PM',u:'TheDustBwlDuck',m:'wait thats MY bind lol'},
{t:'7:53 PM',u:'mikeloveshalflife',m:'of course it is'},
{t:'7:53 PM',u:'dj_n00dles',m:'yo guys check out my new remix'},
{t:'7:53 PM',u:'TheDustBwlDuck',m:'is it the tf2 theme bass boosted again'},
{t:'7:53 PM',u:'dj_n00dles',m:'...maybe'},
{t:'7:54 PM',u:'xXdRuMzXx',m:'our band is gonna be huge'},
{t:'7:54 PM',u:'TheDustBwlDuck',m:'we dont have a band yet'},
{t:'7:54 PM',u:'xXdRuMzXx',m:'ALMOST'},
{t:'7:55 PM',u:'alt_f4_prank',m:'hey new guy press alt f4 for free hats'},
{t:'7:55 PM',u:'just_installed_tf2',m:'really??'},
{t:'7:55 PM',u:'dustbowlBOSS_admin',m:'DONT DO THAT'},
{t:'7:55 PM',u:'alt_f4_prank',m:'lol'},
{t:'7:56 PM',u:'soundboard_guy',m:'*plays sad trombone*'},
{t:'7:56 PM',u:'lenny_face_guy',m:'( \u0361\u00B0 \u035C\u0296 \u0361\u00B0)'},
{t:'7:56 PM',u:'xd_lol_rawr',m:'XD rawr means i love u in dinosaur'},
{t:'7:57 PM',u:'TheDustBwlDuck',m:'its 2010 not 2006 stop'},
{t:'7:57 PM',u:'69_nice',m:'nice'},
{t:'7:57 PM',u:'420_blaze_scout',m:'420 blaze it'},
{t:'7:58 PM',u:'ADMIN_ABUSE',m:'admin ur abusing ur power'},
{t:'7:58 PM',u:'dustbowlBOSS_admin',m:'i literally just muted a spammer'},
{t:'7:58 PM',u:'ADMIN_ABUSE',m:'ABUSE'},
{t:'7:59 PM',u:'votekick_started',m:'*votekick started for ADMIN_ABUSE*'},
{t:'7:59 PM',u:'ADMIN_ABUSE',m:'wait no'},
{t:'8:00 PM',u:'dustbowlBOSS_admin',m:'lol'},
{t:'8:00 PM',u:'TheDustBwlDuck',m:'this server is the best thing ever'},
{t:'8:00 PM',u:'mikeloveshalflife',m:'agreed'},
{t:'8:01 PM',u:'I_MAIN_EVERYTHING',m:'today im a pyro main'},
{t:'8:01 PM',u:'TheDustBwlDuck',m:'u were a heavy main yesterday'},
{t:'8:01 PM',u:'I_MAIN_EVERYTHING',m:'and tomorrow ill be a spy main'},
{t:'8:02 PM',u:'trickstab_god',m:'just got a stairstab'},
{t:'8:02 PM',u:'matador_stab',m:'matador > stair'},
{t:'8:02 PM',u:'cornerstab_pro',m:'corner > both'},
{t:'8:03 PM',u:'deadringer_spy',m:'*fakes death*'},
{t:'8:03 PM',u:'deadringer_spy',m:'*backstabs*'},
{t:'8:03 PM',u:'random_crit_victim',m:'I KNEW HE WAS ALIVE'},
{t:'8:04 PM',u:'HEAVY_IS_CREDIT_TO_TEAM',m:'HEAVY IS CREDIT TO TEAM'},
{t:'8:04 PM',u:'brass_beast',m:'brass beast makes u into a sentry basically'},
{t:'8:04 PM',u:'tomislav_heavy',m:'tomislav is the thinking mans minigun'},
{t:'8:05 PM',u:'natasha_heavy',m:'natascha slows people down its hilarious'},
{t:'8:05 PM',u:'TheDustBwlDuck',m:'i hate playing against natascha heavys'},
{t:'8:06 PM',u:'holiday_punch',m:'*tickles u*'},
{t:'8:06 PM',u:'NEED_HEALING',m:'MEDIC!!! MEDIC!!! MEDIC!!!'},
{t:'8:06 PM',u:'TheDustBwlDuck',m:'IM HEALING U CALM DOWN'},
{t:'8:06 PM',u:'M3DIC_OR_RIOT',m:'medic life is pain'},
{t:'8:07 PM',u:'medic_gf',m:'i only play medic when my bf plays heavy'},
{t:'8:07 PM',u:'TheDustBwlDuck',m:'thats actualy cute ngl'},
{t:'8:08 PM',u:'PAYLOAD_PUSHR',m:'THE PAYLOAD MOVES'},
{t:'8:08 PM',u:'CART_GOES_BRRR',m:'BRRRRR'},
{t:'8:08 PM',u:'n00bkillaXD',m:'IM THE BEST PLAYER ON THIS SERVER'},
{t:'8:08 PM',u:'TheDustBwlDuck',m:'ur score is 3'},
{t:'8:09 PM',u:'n00bkillaXD',m:'TACTICAL SCORE'},
{t:'8:09 PM',u:'pro_gamer_69',m:'pro gamer move right there'},
{t:'8:10 PM',u:'xx_FRAGZ_xx',m:'ggs that was a fun round'},
{t:'8:10 PM',u:'TheDustBwlDuck',m:'GG every1'},
{t:'8:10 PM',u:'mikeloveshalflife',m:'good game'},
{t:'8:10 PM',u:'dustbowlBOSS_admin',m:'gg. next round starting in 30 seconds.'},
{t:'8:10 PM',u:'BONKBONKBONK',m:'GG BONK'}
];

if(typeof pcState!=='undefined'&&pcState===2){
const corrupted=[
{t:'11:00 PM',u:'dustbowlBOSS_admin',m:'Server restarting for maintenance...'},
{t:'11:01 PM',u:'mikeloveshalflife',m:'hey has anyone seen duck lately'},
{t:'11:01 PM',u:'xX_SC0UT_RULEZ_Xx',m:'not for a few days'},
{t:'11:01 PM',u:'PYROMANIAC_99',m:'hes been offline since the 20th'},
{t:'11:02 PM',u:'hevy_sandvich_man',m:'his steam says hes playing tf2 tho'},
{t:'11:02 PM',u:'M3DIC_OR_RIOT',m:'yeah but hes not on any server'},
{t:'11:03 PM',u:'hatcollector3000',m:'something weird happened with his account'},
{t:'11:03 PM',u:'hatcollector3000',m:'i got a trade offer from him. a corrupted item.'},
{t:'11:04 PM',u:'mikeloveshalflife',m:'dont accept anything from his account'},
{t:'11:04 PM',u:'dustbowlBOSS_admin',m:'Im going to be straight with everyone.'},
{t:'11:05 PM',u:'dustbowlBOSS_admin',m:'Something happened on this server about a week ago.'},
{t:'11:05 PM',u:'dustbowlBOSS_admin',m:'A player appeared who wasnt on the scoreboard.'},
{t:'11:06 PM',u:'dustbowlBOSS_admin',m:'Multiple people saw it. Connection logs show 0.0.0.0.'},
{t:'11:06 PM',u:'dustbowlBOSS_admin',m:'I had to shut the server down for 3 days.'},
{t:'11:07 PM',u:'server_regular',m:'wait what'},
{t:'11:07 PM',u:'dustbowl_newbie',m:'is this a joke'},
{t:'11:07 PM',u:'PYROMANIAC_99',m:'its not a joke. i saw it too.'},
{t:'11:08 PM',u:'PYROMANIAC_99',m:'it followed me to css.'},
{t:'11:08 PM',u:'spycrab_lol',m:'ok im scared'},
{t:'11:08 PM',u:'cr1tical_h1t',m:'this is a prank right'},
{t:'11:09 PM',u:'mikeloveshalflife',m:'its not. duck told me about this months ago.'},
{t:'11:09 PM',u:'mikeloveshalflife',m:'he bought a used hard drive. it had old tf2 demo files on it.'},
{t:'11:10 PM',u:'mikeloveshalflife',m:'he played the demos and something... came off them.'},
{t:'11:10 PM',u:'xX_SC0UT_RULEZ_Xx',m:'dude i saw it on dustbowl last week'},
{t:'11:10 PM',u:'xX_SC0UT_RULEZ_Xx',m:'standing in the tunnel. not moving.'},
{t:'11:11 PM',u:'xX_SC0UT_RULEZ_Xx',m:'i tried to shoot it and my game froze.'},
{t:'11:11 PM',u:'hevy_sandvich_man',m:'same thing happened to me'},
{t:'11:11 PM',u:'hevy_sandvich_man',m:'i saw ducks name in the killfeed but he wasnt online'},
{t:'11:12 PM',u:'BONKBONKBONK',m:'im not bonking anymore. this is serious.'},
{t:'11:12 PM',u:'backstabMASTA',m:'ok thats how u know its real'},
{t:'11:13 PM',u:'2FORT_4EVER',m:'its on 2fort too. i saw it.'},
{t:'11:13 PM',u:'tunnel_vision_guy',m:'its on every server ive joined today'},
{t:'11:14 PM',u:'sn1p3r_n0_sc0p3',m:'i tried to headshot it. bullet went thru it.'},
{t:'11:14 PM',u:'random_crit_victim',m:'ok im logging off'},
{t:'11:14 PM',u:'server_lag_247',m:'the server is lagging really bad'},
{t:'11:15 PM',u:'dustbowlBOSS_admin',m:'I can see the connections in the logs.'},
{t:'11:15 PM',u:'dustbowlBOSS_admin',m:'All from 0.0.0.0.'},
{t:'11:15 PM',u:'dustbowlBOSS_admin',m:'Thats not a valid IP. It shouldnt be possible.'},
{t:'11:16 PM',u:'gmod_builder',m:'its in gmod too. i was building and it was just there.'},
{t:'11:16 PM',u:'left4dead_fan',m:'i saw something in l4d2 as well. just standing there.'},
{t:'11:17 PM',u:'css_veteran',m:'its in source games. all of them.'},
{t:'11:17 PM',u:'mikeloveshalflife',m:'it spreads through steam.'},
{t:'11:17 PM',u:'mikeloveshalflife',m:'anyone who connects to a server where its been can see it.'},
{t:'11:18 PM',u:'mikeloveshalflife',m:'and once you see it, its on your machine.'},
{t:'11:18 PM',u:'dj_n00dles',m:'i got a .dem file from ducks account. opened it in audacity.'},
{t:'11:18 PM',u:'dj_n00dles',m:'just static. except at the 2:01 mark theres a voice.'},
{t:'11:19 PM',u:'dustbowlBOSS_admin',m:'Everyone listen.'},
{t:'11:19 PM',u:'dustbowlBOSS_admin',m:'Do NOT connect to 0.0.0.0:27015.'},
{t:'11:19 PM',u:'dustbowlBOSS_admin',m:'Do NOT accept trade offers from TheDustBwlDuck.'},
{t:'11:20 PM',u:'dustbowlBOSS_admin',m:'Do NOT play demo files you didnt record yourself.'},
{t:'11:20 PM',u:'mvm_veteran',m:'this is insane'},
{t:'11:20 PM',u:'just_installed_tf2',m:'i literally just installed this game today'},
{t:'11:20 PM',u:'just_installed_tf2',m:'should i uninstall'},
{t:'11:21 PM',u:'PYROMANIAC_99',m:'yes.'},
{t:'11:21 PM',u:'mikeloveshalflife',m:'honestly... maybe.'},
{t:'11:22 PM',u:'first_time_here',m:'wait is this real or is this some kind of arg'},
{t:'11:22 PM',u:'cr1tical_h1t',m:'i wish it was an arg bro'},
{t:'11:23 PM',u:'sENTRY_gUY_420',m:'gUYS mY gAME jUST cRASHED'},
{t:'11:23 PM',u:'sENTRY_gUY_420',m:'tHERE wAS sOMETHING iN mY sPAWN'},
{t:'11:24 PM',u:'dustbowlBOSS_admin',m:'How many of you have seen it tonight?'},
{t:'11:24 PM',u:'xX_SC0UT_RULEZ_Xx',m:'me'},
{t:'11:24 PM',u:'PYROMANIAC_99',m:'me'},
{t:'11:24 PM',u:'hevy_sandvich_man',m:'me'},
{t:'11:24 PM',u:'2FORT_4EVER',m:'me'},
{t:'11:24 PM',u:'sENTRY_gUY_420',m:'mE'},
{t:'11:24 PM',u:'gmod_builder',m:'me'},
{t:'11:24 PM',u:'left4dead_fan',m:'me'},
{t:'11:24 PM',u:'css_veteran',m:'me'},
{t:'11:24 PM',u:'tunnel_vision_guy',m:'me'},
{t:'11:24 PM',u:'sn1p3r_n0_sc0p3',m:'me'},
{t:'11:25 PM',u:'dustbowlBOSS_admin',m:'Thats 10 people. In one night.'},
{t:'11:25 PM',u:'dustbowlBOSS_admin',m:'A week ago it was just duck.'},
{t:'11:26 PM',u:'mikeloveshalflife',m:'its spreading faster'},
{t:'11:26 PM',u:'hatcollector3000',m:'what do we do'},
{t:'11:27 PM',u:'dustbowlBOSS_admin',m:'Im shutting the server down. For good this time.'},
{t:'11:27 PM',u:'server_regular',m:'no...'},
{t:'11:27 PM',u:'BONKBONKBONK',m:'this was our home'},
{t:'11:28 PM',u:'TheDustBwlDuck',m:'im sorry'},
{t:'11:28 PM',u:'mikeloveshalflife',m:'DUCK??'},
{t:'11:28 PM',u:'xX_SC0UT_RULEZ_Xx',m:'DUCK IS THAT YOU'},
{t:'11:28 PM',u:'dustbowlBOSS_admin',m:'His account shows offline. How is he typing.'},
{t:'11:29 PM',u:'TheDustBwlDuck',m:'i didnt mean 4 this 2 happen'},
{t:'11:29 PM',u:'TheDustBwlDuck',m:'i just wanted 2 play dustbowl'},
{t:'11:29 PM',u:'TheDustBwlDuck',m:'thats all i ever wanted'},
{t:'11:30 PM',u:'mikeloveshalflife',m:'duck where are you'},
{t:'11:30 PM',u:'TheDustBwlDuck',m:'im at home'},
{t:'11:30 PM',u:'TheDustBwlDuck',m:'im always at home'},
{t:'11:31 PM',u:'dustbowlBOSS_admin',m:'Server shutting down.'},
{t:'11:31 PM',u:'dustbowlBOSS_admin',m:'Goodbye everyone. Stay safe.'},
{t:'11:31 PM',u:'mikeloveshalflife',m:'duck please'},
{t:'11:32 PM',u:'??????????',m:''},
{t:'11:32 PM',u:'??????????',m:''},
{t:'11:32 PM',u:'??????????',m:''},
{t:'11:32 PM',u:'??????????',m:'201'},
{t:'11:33 PM',u:'* Server disconnected *',m:''}
];
return{users,messages:corrupted};
}
return{users,messages:normal};
};

const openChatroom=()=>{
const data=getChatroomData();
const isCorrupted=typeof pcState!=='undefined'&&pcState===2;
const serverName=isCorrupted?'Dustbowl 24/7 - FINAL BROADCAST':'Dustbowl 24/7 Community Chat';
let msgHtml='';
data.messages.forEach(m=>{
const isSystem=m.u.startsWith('*');
const isDuck=m.u==='TheDustBwlDuck';
const isAdmin=m.u==='dustbowlBOSS_admin';
const isEntity=m.u==='??????????';
const col=isSystem?'#808080':isEntity?'#800':isAdmin?'#c00':isDuck?'#00c':'#000';
const style=isEntity?'color:#800;font-style:italic':'';
if(isSystem){
msgHtml+=`<div style="font-size:10px;color:#808080;padding:2px 0;font-style:italic;text-align:center">${m.u} ${m.m}</div>`;
}else{
msgHtml+=`<div style="font-size:11px;padding:1px 0;${style}"><span style="color:#808080">[${m.t}]</span> <span style="color:${col};font-weight:bold">${m.u}:</span> ${m.m}</div>`;
}
});
let userHtml='';
const shownUsers=isCorrupted?data.users.slice(0,30):data.users.slice(0,80);
shownUsers.forEach(u=>{
const col=u==='dustbowlBOSS_admin'?'#c00':u==='TheDustBwlDuck'?'#00c':'#000';
userHtml+=`<div style="font-size:9px;color:${col};padding:1px 4px;white-space:nowrap">${u}</div>`;
});
const h=`<div style="display:flex;flex-direction:column;height:100%;background:#fff;font-family:Tahoma,sans-serif">
<div style="padding:3px 8px;background:${isCorrupted?'#4a0000':'#ece9d8'};border-bottom:1px solid #808080;font-size:11px;color:${isCorrupted?'#ff8888':'#000'};font-weight:bold">${serverName} | ${isCorrupted?shownUsers.length+' users (was 247)':shownUsers.length+' users online'}</div>
<div style="flex:1;display:flex;overflow:hidden">
<div style="flex:1;overflow-y:auto;padding:4px 8px;font-family:Tahoma,sans-serif" id="chatroom-log">${msgHtml}</div>
<div style="width:130px;overflow-y:auto;padding:2px 0;background:#f8f8f8;border-left:1px solid #808080">
<div style="font-size:9px;font-weight:bold;padding:2px 4px;border-bottom:1px solid #d4d0c8;color:#808080">Users (${shownUsers.length})</div>
${userHtml}
</div>
</div>
<div style="display:flex;padding:2px 4px;background:#ece9d8;border-top:1px solid #808080;gap:4px">
<input style="flex:1;padding:2px 4px;border:2px inset #808080;font-size:11px;font-family:Tahoma" placeholder="${isCorrupted?'Server is read-only...':'Type a message...'}" ${isCorrupted?'disabled':''}>
<button style="padding:2px 10px;background:#ece9d8;border:2px outset #fff;font-size:11px;font-family:Tahoma"${isCorrupted?' disabled':''}>Send</button>
</div></div>`;
createWindow('chatroom',serverName,580,420,h);
setTimeout(()=>{const log=document.getElementById('chatroom-log');if(log)log.scrollTop=log.scrollHeight},100);
};
